### ISSUE TITLE
Grimoire Magic Meter Timer Broken w/new Cookie Clicker update

### ISSUE THREAD

**Issue by jeffslutzky** [Aktanusa/CookieMonster#1083]
### Bug description

Magic Meter Timer is broken when using Cookie Clicker v 2.048. The text is flashing and changing.

### To reproduce

Turn on Grimoire Magic Meter Timer option

### Browser / Steam / Version

Browser - Chrome version 102

**Comment by domoddball** [comment]
```
Game.Objects['Wizard tower'].minigame.magicBarTextL.innerHTML
'105.952/108 (+0.059/s) (35s) (35s) (35s) (35s)'
Game.Objects['Wizard tower'].minigame.magicBarTextL.innerHTML
'106.079/108 (+0.059/s) (33s) (33s)'
Game.Objects['Wizard tower'].minigame.magicBarTextL.innerHTML
'106.176/108 (+0.059/s) (31s) (31s) (31s) (31s) (31s)
```

innerHTML call to FormatTime is updating 5 times per frame instead of the expected 1
i believe because recent update has changed the behavior of the `Steam`  variable
removing `typeof Steam === 'undefined'` resolves issue on web version, but unsure how to test against steam
https://github.com/CookieMonsterTeam/CookieMonster/blob/dev/src/Main/ReplaceGameElements/NativeGrimoire.js#L24
