### ISSUE TITLE
I don't see the list of "Missing upgrades" or "Missing normal achievements" when those options are enabled

### ISSUE THREAD

**Issue by jeffslutzky** [Aktanusa/CookieMonster#1101]
### Bug description

I don't see the list of "Missing upgrades" or "Missing normal achievements" on the Statistics page when those options are enabled.

### To reproduce

Missing upgrades ON
Missing Normal Achievements ON

Go to Statistics page.

I don't see anything different than when those options are turned off.

### Browser / Steam / Version

Browser - Chrome

**Comment by domoddball** [comment]
![image](https://user-images.githubusercontent.com/32601481/175433966-da206e51-4b68-4828-95cd-9a32c5347f41.png)
![image](https://user-images.githubusercontent.com/32601481/175434034-5dbe41a2-e32c-4e93-b0ae-3788ec7d8a4a.png)

running chrome Version 102.0.5005.115
i am able to see missing upgrades and missing achievements in the stats page when these options are turned on.

if you include screenshots of similar areas on your browser and/or the save file, more investigation can be done,but otherwise i am unable to reproduce following the steps provided

**Comment by jeffslutzky** [comment]
Oh, I realized the problem. I didn't have "Extra Cookie Monster Statistics" turned on. I didn't realize that needed to be turned on for the missing upgrades/achievements to appear.
