### ISSUE TITLE
Option to move/copy "Pop all" button from stats page

### ISSUE THREAD

**Issue by normann1974** [Aktanusa/CookieMonster#126]
Thanks for this excellent tool! Up until now, I always had the "stats" page open when playing because it made popping all wrinklers easy and the other pages where uninteresting. Now that 2.0034 is out with two minigames, I now have the buildings page open all the time for casting spells. This means that I don't have the "pop all" button available unless I switch back and forth between the stats and building pages. So could the "pop all" button be moved or copied to another section on the screen, e.g. above og under the wrinklers so that it's still available to me at all times?

**Comment by Aktanusa** [comment]
I can definitely see this problem, as I myself have the same problem.  I'll think of something.

**Comment by pancholodbrok** [comment]
I personnally spend quite some time on the Stats page, but it is also to monitor easily if I reach the cookies cap for maximum gain on Lucky/Cookie Chain and - I must admit - keep track of my missed golden cookies. And also because a black background makes easy to spot the golden cookies (especially the seasonal ones). I don't know if this is possible, but I'd rather like to have the minigames accessible from the stats page than moving stuff from there to the main page.

**Comment by Aktanusa** [comment]
Mini games on the stats page sounds harder to do to me.
