### ISSUE TITLE
NaN when cookies per second == 0

### ISSUE THREAD

**Issue by Insane96** [Aktanusa/CookieMonster#156]
![immagine](https://user-images.githubusercontent.com/7185104/33525083-675ff39c-d828-11e7-9d49-23c857ee9827.png)

**Comment by Aktanusa** [comment]
I don't think this is a problem since you can't divide by zero, but I'll take a look.

**Comment by Kidsheldon** [comment]
I mean, while it _is_ NaN according to the calculation, the actual required amount would be 0 and the rewards would all be identical to the (CUR) ones. I think it should set those values instead of calculating if your CPS is 0.

**Comment by Insane-96** [comment]
I mean, maybe displaying 0 or N/A would be better

**Comment by Aktanusa** [comment]
I don't think it be useful to store that information to display for such a short buff not happening 99% of the time.  Not like you want to buy stuff anyway while the buff is on and should be clicking the cookie...

Changing it it to display 0 or N/A aka still not useful information, what is the difference?

**Comment by Kidsheldon** [comment]
> Changing it it to display 0 or N/A aka still not useful information, what is the difference?

The difference is that NaN looks like you forgot to consider a certain case, resulting in a bug, while showing proper, albeit useless values shows that you considered everything.

According to the wiki, "Golden Cookies will not start chains until you have at least 100,000 cookies baked all time." I don't have code from the game to support this, and I'm currently unable to look through said code since I'm at school and Cookie Clicker is blocked, but it shouldn't be too hard to find it.

**Comment by Insane-96** [comment]
> The difference is that NaN looks like you forgot to consider a certain case, resulting in a bug, while showing proper, albeit useless values shows that you considered everything.

This
