### ISSUE TITLE
Calculation error

### ISSUE THREAD

**Issue by egerke28** [Aktanusa/CookieMonster#200]
On the attached savefile the addon calculates mines clearly wrongly, saying they are the best with a negative bonus income, until then after a while snapping back to correct calculations, showing that mines are actually the worst, due to me being fooled by the error a few times.

![cookie bug](https://user-images.githubusercontent.com/38431774/40981630-ac6ff7a4-68db-11e8-93e0-081f67168f75.png)
[Cookie bug save.txt](https://github.com/Aktanusa/CookieMonster/files/2072701/Cookie.bug.save.txt)

**Comment by Aktanusa** [comment]
Wow, this seems like a serious bug.  Thanks for the save file!  I'll take a look.

**Comment by Aktanusa** [comment]
Hmm, I loaded your save in a new window with the same version of CM and I don't see the problem.  That's not going to make it easy to figure out =/

**Comment by egerke28** [comment]
Windows 10 64-bit and Firefox 60.0.1 (32-bit). Settings attached.
![cookiesettings](https://user-images.githubusercontent.com/38431774/40993840-f1b9b150-68fa-11e8-8711-3e49c89d918c.png)
![cookiesettings2](https://user-images.githubusercontent.com/38431774/40993842-f3e6d4f8-68fa-11e8-8cac-557d464a758c.png)

**Comment by Aktanusa** [comment]
Just curious, why aren't you using 64-bit Firefox?  Also, if you open a new private window in Firefox and load your save file above, does it show negative bonus income?

**Comment by egerke28** [comment]
I use 32 bit because when I installed that was the recommended one. Loading the save in private window gave this: (still negative numbers) and then flipped to normal in about 10 seconds.

![cookie bug 3](https://user-images.githubusercontent.com/38431774/41043703-c75203c2-69a4-11e8-8a7f-fa8ad21f228c.png)

**Comment by Aktanusa** [comment]
Hmm, I didn't get that when I tried it, but I'm on 64-bit Firefox.  I guess the next question is, what order did you do?  Open private window, go to CC, load CM, then load save or open Private window, go to CC, load save, then load CM?

**Comment by cjenn** [comment]
I'm having a seemingly similar issue.

it just started today, seemingly at random. (I didn't update anything, but it may have done that on its own. I've been playing the game for about a week)

it was initally just changing back/forth between seemingly reasonable estimations.

I gained about a 2 sextillion cookies (it's a new save, previously it only had ~300 quintillion cbat), and 
now it's stuck showing negative numbers.

the problem seems to be worst with mines/farms/factories

I've cleared the cache/cookies, and checked the console, but everything appears to be normal

I'm running (64-bit) firefox 60.0.2 on ubuntu 16.04.

I'm not able to upload anything, as I'm on vacation with terrible internet, but i'll be able to post screenshots/check with other browsers when I'm home in ~2 days

**Comment by cjenn** [comment]
[save](https://gist.github.com/cjenn/393a26a23706b1a0a7d8afb8472696d3)

**Comment by cjenn** [comment]
taking/revoking the elder covenant does nothing. neither does changing aura.

**Comment by cjenn** [comment]
reslotting cyclius seems to recreate the problem.
removing him again seems to fix it. (i just wasted 2 worship slots for you, i hope you feel good about yourself)

It's worth noting that I've played with cyclius on before, (for a week, i mean), and I never had a significant issue.

off the top of my head, mostly so I don't forget, here are things that I've done in the past few hours, that might make a difference:

- Unlocked White/Normal Chocoroot, Gildmillet
- Triggered the grandmapocalypse
- fed banks <-> shipments to krumblor, switched to dragonflight

I'll play around in incognito/mess with the garden tomorrow before I leave

**Comment by cjenn** [comment]
Oh, also, I reset the settings to default (about 3 comments back), and that didn't really do anything.

**Comment by Aktanusa** [comment]
Thanks for more information I can go test with @cjenn.  I'll test in a bit.

If you weren't joking about "(i just wasted 2 worship slots for you, i hope you feel good about yourself)", that's on you, as you should have tried it in a new private window =p.

**Comment by Aktanusa** [comment]
Oops, I forgot about this, testing now.

**Comment by Aktanusa** [comment]
Okay, using @cjenn's save, I sometimes see the problem.  I have an idea of why it's happening and unfortunately the fix is not easy as I may have to slightly modify how the game works (maybe), but without the bug showing up consistently, it be hard to know if it's fixed.  I guess you guys would need to try it.  I suspect it will show up more on slower computers also.

**Comment by Aktanusa** [comment]
Fixed in Version 2.106.2.  Let me know if you still see this problem and I'll reopen it.
