### ISSUE TITLE
Calculate clicks-to-payback instead of PP for cursor upgrades

### ISSUE THREAD

**Issue by 9999years** [Aktanusa/CookieMonster#254]
Some upgrades only effect cookies gained by clicking the big cookie, but these are always (?) shown as having an infinite payback time; could we display the number of clicks before the upgrade would be paid off, or the potential increase in cookies/click, or something like that?

I might have some time to implement this within a few weeks.

**Comment by Aktanusa** [comment]
There was a thought to do that, but I have not gotten around yet.  I currently have other things as higher priority, but I do want to still work on my addon.  It would be great for you to have it implemented, but on the flip side, I would feel bad in taking forever to add it in.

**Comment by 9999years** [comment]
Thanks for the quick reply! Can you point me to the function(s) that might need to be modified? The codebase is... a little unclear to me at the moment.

**Comment by Aktanusa** [comment]
do you mean where in CM to modify or where in the game to look at?

**Comment by 9999years** [comment]
Where in CM to modify.

**Comment by Aktanusa** [comment]
Disp.js is where the tooltip is created and pulling data.  Cache.js is where the data is stored.  Sim.js is where the data is calculated.  You probably want to calculate the data and store it in cache before it is pulled from the tooltip in Disp.js.  In terms of what functions to modify, there are none in Cache.js and Sim.js as they don't exist.  You need to make them.  In Disp.js, you would probably need to modify a tooltip function as it right now pulls the efficiency data.  Off from memory, there should be one function to setup the static structure of the tooltip for upgrades and then the update tooltip function would replace the data depending on the tooltip type.  Since you are making a new tooltip type for clicking upgrades, you probably need to setup a new static structure and type besides of 'u' 'b' and I think 'g' for grimoire tooltips.  Hope this helps.  This is by no means an easy enhancement to implement, honestly.

**Comment by 9999years** [comment]
OK, great, thanks!

**Comment by DanielNoord** [comment]
This can be implemented together with #231
