### ISSUE TITLE
Cursed Finger changes the requirements and MAX rewards for Lucky/Chain to Infinity

### ISSUE THREAD

**Issue by Kidsheldon** [Aktanusa/CookieMonster#267]
0 CpS, fresh save. Requirements are 0 and MAX rewards are 13 and 7/6 respectively, as they should be.
![image](https://user-images.githubusercontent.com/17099837/66440657-c3a8d780-ea01-11e9-8405-e0fac3721bc1.png)

With Cursed Finger active. Requirements and MAX rewards change to Infinity.
![image](https://user-images.githubusercontent.com/17099837/66440697-f0f58580-ea01-11e9-8a0c-5a6c8166a32f.png)

**Comment by Chorizorro** [comment]
It seems this issue is the same as #156, the only difference being Chromium-based browsers handle "Infinity" when dividing by zero, whereas other browsers keep the good ol' "NaN".

As the stats shown when CpS == 0 when beginning a new game are "0" (as seen in the first screenshot), I suppose the best we can do is showing "0" everywhere instead of "Infinity" / "NaN" during Cursed finger?

**Comment by DanielNoord** [comment]
Yeah, that seem the best approach and actually correct.
