### ISSUE TITLE
Change from BCI to more efficient method

### ISSUE THREAD

**Issue by Aktanusa** [Aktanusa/CookieMonster#3]

**Comment by svschouw** [comment]
As you mentioned this issue again and said you were a bit lazy to implement it I would at least point you to my implementation svschouw@bf33a1d6dbfb0ad2569a6a7382f0026dbfa47653.

If you want I can make a proper pull request.

There are also some other goodies on my https://github.com/svschouw/CookieMonster fork, like some code to help me determine whether it's best to buy an upgrade now, or wait until I have enough "Lucky!" cookies. But those commits are pretty raw.

**Comment by Aktanusa** [comment]
I'll take a look, thanks!  And sorry for the wait, this enhancement has been open for a long time now, lol.  Most likely this weekend is when I will have free time.

**Comment by Aktanusa** [comment]
@svschouw I've taken a look at your code and I'm processing it now.

Off-topic:  I was wondering what is Golden CPS support in your later commits?

**Comment by Aktanusa** [comment]
@svschouw I reread what you wrote above and this part "But suppose you also had a third upgrade: c.cost = 400, c.cps=900 => c.bci = 2.25..." the BCI is 400/900 = 0.4444... not 2.25 in which it should be bought first.

**Comment by svschouw** [comment]
@Aktanusa Hmm, you're right; I confused the division. I tried to make the point that in some cases buying the one that gives the most upgrade is better than the ROI (let's call it that) formula, but in other cases it isn't. Although, clearly, an upgrade with 900 cps for 400 is even the best in that regard.

@Aktanusa About the "Golden CPS support", that tries to calculate your effective CPS if you were to click on the golden/wrath cookies every time it pops up. That depends on a lot of factors, including how many cookies you have (for the Lucky! cookie), but it can be up to 30x higher than your normal CPS. It displays what the change in golden CPS would be if you buy an upgrade/building, which I mostly use to see if I should buy an upgrade/building immediately or if I should wait for more cookies.

But it's pretty raw. For example, it assumes you get a golden cookie every 120 second, taking into account lucky upgrades, but not golden cookie upgrades (those that will make it appear 5% faster for example), because the exact calculations are very tricky and expensive (since it's basically a bell curve). Also it uses some very old simulation results about cookie chains. That said, I still think it is useful. But maybe complete discussion about it is something for another topic.

**Comment by Aktanusa** [comment]
So I did some simulation with different cookies in bank amount.  Using the same example as you did, building 0 cost 100 and adds 100 CPS, building 1 cost 1000 and adds 110 CPS, and building 2 cost 400 and adds 900 CPS, here is what I got:

Bank: 0.0
0 1 2 1011.8938652970066
0 2 1 1004.995904006003
1 0 2 10002.812120520439
1 2 0 10003.73206095277
2 0 1 4001.1109987768023
2 1 0 4001.209987767037
Lowest: 1004.995904006003

Bank: 100.0
0 1 2 11.89386529700666
0 2 1 4.995904006002997
1 0 2 9002.812120520439
1 2 0 9003.73206095277
2 0 1 3001.1109987768023
2 1 0 3001.209987767037
Lowest: 4.995904006002997

Bank: 400.0
0 1 2 8.896862300003662
0 2 1 1.998901008999999
1 0 2 6002.812120520439
1 2 0 6003.73206095277
2 0 1 1.1109987768026885
2 1 0 1.2099877670369839
Lowest: 1.1109987768026885

Bank: 500.0
0 1 2 7.897861301002663
0 2 1 0.9999000099990001
1 0 2 5002.812120520439
1 2 0 5003.73206095277
2 0 1 0.9999000099990001
2 1 0 1.0988890002332954
Lowest: 0.9999000099990001

Bank: 1000.0
0 1 2 2.9028563059976675
0 2 1 0.49995000499950004
1 0 2 2.8121205204389934
1 2 0 3.7320609527694
2 0 1 0.49995000499950004
2 1 0 0.543395166214853
Lowest: 0.49995000499950004

Bank: 1100.0
0 1 2 1.9038553069966684
0 2 1 0.3999600039996
1 0 2 1.9038553069966684
1 2 0 2.8237957393270747
2 0 1 0.3999600039996
2 1 0 0.43229639941116443
Lowest: 0.3999600039996

Bank: 1400.0
0 1 2 0.4759638267491671
0 2 1 0.0999900009999
1 0 2 0.4759638267491671
1 2 0 0.099000099000099
2 0 1 0.0999900009999
2 1 0 0.099000099000099
Lowest: 0.099000099000099

Bank: 1500.0
0 1 2 0.0
0 2 1 0.0
1 0 2 0.0
1 2 0 0.0
2 0 1 0.0
2 1 0 0.0
Lowest: 0.0

At first with low bank, the best order is 0 2 1, then it switches to 2 0 1. which then switches to 2 1 0 before not mattering if you can just buy three.

**Comment by Aktanusa** [comment]
Due to talks in Issue #68, it got me thinking.  Instead of using the formula max(cost - cookies in bank, 0)/cps + cost/Δ cps, why not change it to the formula max(cost - cookies in bank, 0)/cps + cost/(cps + Δ cps)?  It would then really be the "Payback Period" in terms of seconds to when it will "break even".  Thoughts @svschouw?

**Comment by svschouw** [comment]
well, if you change the second component from cost/Δcps to cost/(cps + Δcps) you take the time until you have the same amount of cookies as the moment you bought it, but by everything. So if you have 90cps and you have an item of 1000 cookies giving 10 cps, it will take 10 seconds to get back to where you were. But 90% of that is due to other things you have. So the item only contributed to 100 cookies of that. And I don't think you would want that. You want to see how long it takes for the item to pay for itself.

Another way of looking at it is: if you have a very huge CPS already compared to what you can buy, right component reduces to 0, so then the algorithm basically favors the items you can buy first, regardless of profit.

Also, changing listed cps to actual (or effective) cps does not matter if the actual cps is just a constant factor over the actual cps. Because you are just reducing the result by that factor. Although it might be a good reason NOT to include an actual unit, since it's meaningless in the face of wrinklers and golden cookies. But I don't care much either way.

**Comment by Aktanusa** [comment]
Well good thing I asked!  Apparently I brainfarted and thought it was just a constant 1/cps multiplication to the right side.  No idea what I was thinking, lol.

I'm confused as to why I shouldn't use the average CPS.  I thought using the average CPS accounts for wrinklers and golden cookies.

**Comment by svschouw** [comment]
First of all, you need to know Δecps (the change in effective cps by buying the upgrade). Otherwise you are just comparing apples and oranges. But suppose you just calculate F = ecps/cps and then do Δecps = Δcps * F. Then the eroi formula becomes eroi = max(cost - cookies, 0)/ecps + cost/Δecps = max(cost - cookies, 0)/(F\*cps) + cost/(F\*Δcps) = [max(cost - cookies, 0)/cps + cost/Δcps] / F = roi / F.
So you're just multiplying the current ROI calculation with a constant 1/F factor. It really doesn't matter, but like you said: the numbers will fluctuate wildly which I'm not a fan of.

**Comment by Aktanusa** [comment]
Hmm, very good point.  So in the end the formula still is the same.  Thanks again for your thoughts!  I'm no math person, lol.

**Comment by Aktanusa** [comment]
While it is a common multiplier so the order wouldn't change, but currently any type of frenzy changes the numbers since the current CPS is calculated that way.  A fix would be just recalculate the CPS w/o the frenzy, but should I do it?

**Comment by svschouw** [comment]
I am a bit of a math person :). Good point about the frenzy. I remember a bit of code which undid the frenzy, but that could just be my own golden CPS calculations. So yeah, if your goal is a stable number, then undoing the frenzy multiplier could be a good idea.

**Comment by Aktanusa** [comment]
How about adding wrinklers to the formula?  

max(cost - cookies in bank - wrinkler sucked cookies, 0)/cps + cost/Δ cps

**Comment by svschouw** [comment]
You could technically count them as cookies you have to spend, so sure.

**Comment by Aktanusa** [comment]
I'll probably make it an option to add wrinkler sucked cookies to bank in calculations

**Comment by DanielNoord** [comment]
The only problem in this thread that has not been solved can be found in #4 
Therefore, I am closing this issue!

**Comment by Aktanusa** [comment]
@DanielNoord Actually, our current calculation is not perfect.  I actually wrote many years ago a solution in pure Java using dynamic programming on a way to find an even more efficient method.  If you would like to implement it, I can go find that code and post it somewhere.  It's pretty CPU intensive though.  Up to you if you want to reopen this.

**Comment by DanielNoord** [comment]
Hm, could you explain what is wrong with the current calculation?

I am not really in favor of making CM more CPU intensive though, so I am not sure if I would like to add that.

**Comment by Aktanusa** [comment]
> 
> 
> > True, buying a could improve the the cps in such a way that now c becomes more viable than b. But the real question is whether a is always the best first option? Or is there an example where the best buying order starts with either b or c?
> 
> There are example where the best buying order doesn't start with a. For example:
> 
> Current CPS = 226.5785735502662
> a.cost = 747.929200617538
> a.cps = 681.6778533572583
> b.cost = 742.0998752732398
> b.cps = 699.5548482909151
> c.cost = 348.9248174870489
> c.cps = 129.09762796633072
> 
> Using cost/cps + cost/Δ cps, the buying order would be:
> 
> c, b, a
> 
> taking 4.335203035965191 seconds while the better order:
> 
> b, a, c
> 
> would take 4.299844025685106 seconds.
> 
> > Also, with the help of that friend I found an easy counterexample as to why MAX((cost) - (current cookies), 0) / cps + (cost)/Δcps is still incorrect:
> > Given (current cookies) = 1000, a.cost = 100, a.cps = 100, b.cost = 1000, b.cps=110, cps=0.1, my formula would break down to basic BCI (since MAX(cost - cookies, 0) = 0).
> > But a.bci = 100/100 = 1 and b.bci 1000/110 = 9.9, which would say a is the better choice. However, first buying a would require you to wait a further 1 second to buy b, but first buying b would only require 0.9 seconds to buy a. So a, b is the best order. Basically, given the choice between only two already affordable upgrades, buy the one which gives the most increase.
> 
> I think you mean the best buying order is b, a?
> 
> Yep, this is a complex problem. I really wish some math person would just figure out a best formula for us, lol. Maybe your friend can do it (heh)?
> 
> Currently, my plan is to implement a somewhat approximation of the best buying order via doing something like this:
> 
> Take a base order using cost/cps + cost/Δ cps, so for example a base could be:
> 
> a, b, c, d
> 
> Then go through all combinations of moving one item around:
> 
> moving only a:
> b, a, c, d
> b, c, a, d
> b, c, d, a
> 
> moving only b:
> b, a, c, d
> a, c, b, d
> a, c, d, b
> 
> moving only c:
> c, a, b, d
> a, c, b, d
> a, b, d, c
> 
> moving only d:
> d, a, b, c
> a, d, b, c
> a, b, d, c
> 
> And then repeat as base when a new more efficient order is found. This is n_(n-1) combinations which is a lot less than n! combinations. Now looking at my own example, I even notice even more repeats, so really it's less than n_(n-1) combinations. Hopefully again you get what I mean, but yes you brought in new complexities by figuring out what is the best order when you have the cookies to buy already, lol.

I already explained it in this thread.  I basically implemented this in Java.

**Comment by DanielNoord** [comment]
Hmm this still seems like quite a bit of computations.

I was wondering in what scenario's "buying current lowest pp building" is not the optimal strategy.
Is the situation you describe an actual real scenario in the game? Or is it just imagined?
And if it is, can we describe the situation in general? For example, "When building a and b are on the same level".

The only situation I currently know is when "A building can reach the x amount of building achievement".
This situation would be fairly easy to implement (I think). We can cache the cookies needed to reach the next achievement threshold and check during calculation of PP's for each building if the user has passed the threshold and change the pp accordingly. 
We could even make this the standard behavior: 1) Cache cookies till next threshold, 2) Compute PP of going to threshold, 3) Compare threshold-pp with next-building-pp, 4) if thershold-pp is lower show that one.

I believe this will be the most important moment when "buying current lowest pp building" is not the best strategy, but I am not sure. So please do tell if there are any other situation where it is not the best strategy and if they can be generalized.

**Comment by Aktanusa** [comment]
To be honest, it is just in theory.  The problem is, I don't really have a way to test if it will ever happen in game.  This has nothing to do with chain buying yet either.  That's a different issue.

Off topic:  For chain buying, like you are thinking, we would need to calculate for every achievement not already earned and store it as cache that would be needed to recalculated every time something changes.  I had ideas, but never got already to implementing them.  The other old popular addon, FrozenCookies, already had chain buying there.

**Comment by DanielNoord** [comment]
Do we have the old code of FrozenCookies somewhere?

**Comment by Aktanusa** [comment]
It's on GitHub somewhere.
