### ISSUE TITLE
Show average purchase value of owned stock

### ISSUE THREAD

**Issue by ingesiit** [Aktanusa/CookieMonster#307]
Sorry for the request, I know that time is not in your availability, but I'd like to leave anyway a suggestion about the Stock market.
When you buy items, you can no longer see in game the purchase cost, and you have to remember it (or write down somewhere) to decide if/when sell
So, a useful implementation may be a tooltip that says the average purchase cost of the stock.
Thank you anyway for your effort
Kind regards

**Comment by Silvermann17** [comment]
Might be I'm wrong, but wouldn't this be solved by only buying while the stock's in the red and only selling when it's in the green?

**Comment by staticvariablejames** [comment]
The reds and greens of the stock market are relative to the previous tick, so this not enough.

There are mods with this functionality already; I'm aware of <https://github.com/darthpilou/EZStock>

**Comment by Silvermann17** [comment]
Ah, you're right. That link didn't work for me, but I found [one that did and seems really good](https://github.com/staticvariablejames/InsugarTrading). Basically, when the quantiles that appear under the stock values are orange and bold: buy/sell as many as you can, depending on if you have a little or a lot. And it works with Cookie Monster!

**Comment by DanielNoord** [comment]
I have used the InsugarTrading mod as well, and it works perfectly.
Paging @staticvariablejames to see if he thinks 1) Cookie Monster can add anything to enhance InsugarTrading, or if 2) we can add anything that makes it easier for people to find InsugarTrading.
Otherwise, this issue can be closed.

**Comment by staticvariablejames** [comment]
Insugar Trading shows long-term statistics about the stocks, whereas OP asks for saving the price the stock was bought at. It is true that adopting the rule of only selling above and buying below a certain threshold makes recording stock prices unnecessary (and Insugar Trading makes following this rule very easy), but they are problems of different nature.

Regarding cooperation between Insugar Trading and Cookie Monster: I don't think that there is anything that could be enhanced here other than making sure we don't step on each other's toes. Insugar Trading is fairly well-behaved in that it never injects code directly, always relying on the hooks injected by [CCSE](https://github.com/klattmose/klattmose.github.io/tree/master/CookieClicker/CCSE-POCs). As long as CCSE and CM are compatible, there shouldn't be any clashes between Insugar Trading and Cookie Monster. (I could imagine Cookie Monster adding a notification for when a stock drops below or rises above a certain quantile threshold, and then CM can query Insugar Trading for the corresponding value, but this would have limited usefulness.)

But then again Cookie Monster does very little with respect to banks.

**Comment by DanielNoord** [comment]
Hmm, do you think that saving the average buy-price is something InsugarTrading should add, or do you think it fits better with CM?

**Comment by staticvariablejames** [comment]
I'm conflicted on this matter.

My main issue is that, objectively speaking, knowing the price the stock was bought induces sunk cost bias. Implementing this feature would only help players make worse decisions in the long run.

If either Insugar Trading or Cookie Monster were to implement this feature, I think CM would be a better fit. Insugar Trading is focused on displaying long-term statistics about the stock market. I implemented other stock market goodies (like saving the stock market history) in my other mod [Spiced Cookies](https://github.com/staticvariablejames/SpicedCookies#save-the-history-of-stock-market-prices-enabled-by-default). CM, on the other hand, already has a bunch of goodies like notifying golden cookies and garden ticks and warning about optimizing Luckies, so saving the stock prices would not be out of place.

_However_, that is a horse of a different color: all persistent data stored by Cookie Monster are merely settings. This piece of data is actual save game data, which belongs together with the player's save. Simply using a `localStorage` key introduces the possibility of game data and mod data getting out of sync, so this would require some restructuring inside CM to use the modding API. (CM should use the modding API to store settings anyway, but since they are only settings, I don't think it is a priority now.)

So, although CM would be the best place for this feature, it would be more convenient to implement it in Spiced Cookies (because it already uses the modding API). I'm willing to implement it there, unless you'd prefer to have it in CM.

**Comment by DanielNoord** [comment]
I am not sure what I personally prefer.
I agree that it seems to fit better with the general "goodies" CM offers and would therefore seem to fit here. But then we would first need to rewrite CM to conform to the modding API (which we should do anyway).
Perhaps we should leave this issue for a moment and focus on some others first and come back later.

**Comment by DanielNoord** [comment]
Closing this as, after additional thoughts, I do not think CookieMonster should save any data for the user. There are other mods where this functionality would fit better!
