### ISSUE TITLE
Transfer of Ownership?

### ISSUE THREAD

**Issue by bitsandbytes1708** [Aktanusa/CookieMonster#315]
I don't mean to insult @Aktanusa ,I understand life can get very busy sometimes. But could you consider transferring ownership of this repo to someone who has more time to sort through the pull requests and keep everything updated?

**Comment by DosParkers** [comment]
I just wanted to stop by and say that I use this addon 24/7 and really, really appreciate it. Looking forward to a mini-update. I think the only real issues are the dragon scale upgrade and the eternal heart biscuit.

**Comment by spiderlover0909** [comment]
I wouldn't say I want a complete change of ownership unless

**Comment by spiderlover0909** [comment]
I wouldn't say I want a complete ownership change unless @Aktanusa wants to do that, but I think an assistant would help a lot.

**Comment by bitsandbytes1708** [comment]
@spiderlover0909 I'm fairly certain only the owner of the repo can accept/decline pull requests.

**Comment by Eggsukr** [comment]
Yeah he's been building up a lot of issues and hasn't gotten to them so I think an assistant would be great for those

**Comment by bitsandbytes1708** [comment]
I hope @Aktanusa sees this soon. Thank you in advance for reviewing this issue!

**Comment by chiffon-rouge** [comment]
Since CookieMonster is on Github it could be forked and the pull requests could be applied by hand. Unfortunatly I'm really stupid and wasn't able to make it work, but someone who actually knows what he's doing might be able to do so, at least as a temporary solution until Aktanusa has time to look into this.

**Comment by bitsandbytes1708** [comment]
@chiffon-rouge Maybe, yeah...unfortunately, everything will take several hours just due to all the backup(most of the time spent resolving conflicts). I think it may be a good temporary solution though. If no one replies to this in a few days I might attempt to do it.

**Comment by Aktanusa** [comment]
Sorry I'm late!  Is there an option to add an assistant?  I guess I should go figure that out myself, lol.  I am sorry but I really lack time recently.  So interesting that it happens during a pandemic, lol.  I had so much time near the beginning of it.  Whoops, a side rant.  Anyway, forking is what normally people do to continue on the work of a dying repository.  I had really hope this repository doesn't die, but I'm not sure when I would have time to really look.  I'm thinking next vacation, like maybe Thanksgiving.

**Comment by bitsandbytes1708** [comment]
@Aktanusa I just Googled this, :), but there is a way to give someone "Collaborator" permission if you don't want to give up the repository. Go to the settings page of this repo, select Manage Access, click Invite a Collaborator,then enter the Collaborator's name.

**Comment by bitsandbytes1708** [comment]
Thanks for considering this!

**Comment by Depado** [comment]
Yes, you can define what a collaborator can and can't do. That's basically what we call maintainers and they can help you with that :+1:

**Comment by DosParkers** [comment]
Who's a good pick for being a collaborator?

**Comment by sputtering** [comment]
> Since CookieMonster is on Github it could be forked and the pull requests could be applied by hand.

@chiffon-rouge had the right idea. This is an open source project, and that makes adding things easier. If you can make the changes, fork this project and do so. Then @Aktanusa can fold them into here, or if not, yours becomes the new version to use.

**Comment by DanielNoord** [comment]
The problem is that the wiki etc. will keep linking to this repository which makes working on another repository less useful, as many users might not see the work being done. Furthermore, @Aktanusa does not seem to have the time to actually merge the other repositories. There are already two working PR's (#319 & #321) which could have been merged 11 days ago. Both of them solve all current mod-breaking issues.

I think it would be in the best interest of the community/mod to add a collaborator to @Aktanusa's repository as then those who want to can keep developing and expanding the mod while it remains easily findable for (new) community-members who might not be as fluent in GitHub and repositories.

**Comment by bitsandbytes1708** [comment]
@DanielNoord Yes, it would be good to have a collaborator.

**Comment by chiffon-rouge** [comment]
@DanielNoord This was exactly my problem. There doesn't seem to be a quick solution other than adding someone to actually work in _this_ repo. Earlier @bitsandbytes1708 said he might look into forking this repo. Would you consider asking @Aktanusa to add you as a collaborator in this repo?

**Comment by bitsandbytes1708** [comment]
@chiffon-rouge I don't know if you mean DanielNoord or me, but if @Aktanusa sees this I would be willing to be a collaborator. Also, chiffon-rouge, I did try to fork this repo and I was looking to set it up and there was just too many things to change. I think the only practical thing is to add a collaborator.

**Comment by chiffon-rouge** [comment]
I meant you and I did the same and gave up. ;)

**Comment by bitsandbytes1708** [comment]
@chiffon-rouge Ah, ok :)

**Comment by Aktanusa** [comment]
Sorry for the delay response.  So from what I have read, @bitsandbytes1708 is willing to be a collaborator.  Is there anyone else who would want to collaborate too?  With my lack of time, I am hoping to finally get some time during Thanksgiving, as this year, the great year of 2020, we would all have more time at home, lol.  I don't know if people would be more willing to wait for that.

**Comment by chiffon-rouge** [comment]
@Aktanusa I don't want to sound rude but wouldn't add @bitsandbytes1708 to the repository take, like, mere seconds? Or is there more to it, GitHub-wise? I believe everyone here would appreciate it if this could be done rather sooner than later. If you want to add other people as well, this could still be done at a later date, say Thanksgiving or whenever you have the time to consider additional "staff". Ultimately it's your call, of course, but adding bitsandbytes1708 now could be a quicker solution, as most stuff seems to be fixed in pull requests already anyway – and then again, some pressure off your back as well, no? Thanks! :)

**Comment by bitsandbytes1708** [comment]
@chiffon-rouge I think @Aktanusa is going to add me soon, I think by "finally get some time during Thanksgiving" they meant that they could start doing the pull requests instead of a collaborator.

**Comment by chiffon-rouge** [comment]
I see, your right. I misunderstood. Sometimes I'm oblivious to the finer aspects of your language.

**Comment by bitsandbytes1708** [comment]
@chiffon-rouge That's ok :)

**Comment by bitsandbytes1708** [comment]
@chiffon-rouge Hmm...you might be right. @Aktanusa , would you mind adding me soon?

**Comment by DanielNoord** [comment]
I would also be available to clean up the repository a bit. So if @Aktanusa wants to add 2 collaborators you could also add me! :)

**Comment by Aktanusa** [comment]
Hi all.  Thank you for trying to keep this mod alive.  I want to be completely frank.  The reason why I have been hesitant in terms of adding a collaborators is that I feel like I am losing control over my mod.  I am used to knowing how everything works on my mod and I am slow to adding pull requests because I want to completely understand what I am putting into the mod before actually committing.  For this, I am sorry that I have failed to add many useful pull requests done by other people.  This mod is my baby, and I don't want to lose control =/.  That said, I now have other priorities in life and my time to work on this mod is pretty much non-existent.  I would have liked to be the only one in control of this repository, but I now see that I need to let go.  I don't want this mod to die due to my selfish needs.  Sorry for taking so long to come to this decision.  @bitsandbytes1708 and @DanielNoord, github doesn't really have a way to talk in private.  I would like to talk to you both on some guidelines I would like both of you to follow when working on this mod.  Any suggestions?  Discord? IRC? Email?  Thank you all for being patient with me.

**Comment by DanielNoord** [comment]
I understand where you are coming from and it is why I initially suggested a good clean-up of the repository and leaving the codebase to your discretion. If @bitsandbytes1708 and I clean-up the repository it should not take you too much time to review individual PR's and approve/disapprove them (bearing in mind that you don't need to code, but only review code). I can understand that at the moment you are not really motivated to work on the project as there are so many open issues and PR's.

However, I do believe that you need to be willing to consistently put in some work to review those PR's. I have seen some of your responses to PR's in 2018 and 2019 where you indicated you would review them. It is not good for the health of the project if we have to wait for two years for you to make a decision on PR's.

I do not really use Discord or IRC so email would be to only option for me. Although I believe GitHub offers some ways for collaborators to discuss privately.

**Comment by bitsandbytes1708** [comment]
@Aktanusa Sorry it took me a bit to reply to this, I was on a different computer today. I'm ok with Discord or Email, tell me which account info you need.

**Comment by 4nd3r5** [comment]
@bitsandbytes1708 : I would recommend that you put your contact info on your profile temporarily to speed things up, then you can always remove it again when @Aktanusa has reached out to you.

**Comment by Aktanusa** [comment]
I found out github does have a way to communicate.  I am just waiting for @bitsandbytes1708 to accept the invitation.

**Comment by faulk28** [comment]
Can you please add more developers to speed up development? Thanks for all your hard work on this project.

**Comment by Aktanusa** [comment]
It's coming soon.. Thanks for being patient with me!

**Comment by bitsandbytes1708** [comment]
This has been mostly resolved, so I'm going to close it.
