### ISSUE TITLE
Bonus income calculations broken after reaching 400 upgrades

### ISSUE THREAD

**Issue by toothstone** [Aktanusa/CookieMonster#322]
My current run is stuck with broken bonus income calculations, every building and upgrade available is labeled as if it were to provide at least a 2% CPS increase. At my current milk levels this would suggest that CM somehow thinks I'll add another achievement through acquiring anything.

This possibly started after reaching the 200 idleverse & bicentennial achievement simultaneously, as well as getting the 400 upgrades achievement shortly after that.
I've not yet found a way to reset CM or any other workaround, will report back after my next ascension.

I've included my savefile:
[bakery_broken_cm.txt](https://github.com/Aktanusa/CookieMonster/files/5529377/bakery_broken_cm.txt)

**Comment by Chorizorro** [comment]
Hello, this is most likely due to the plugin not having been officially updated since 2.021. There are some similar issues opened on this matter.

To fix this, you can use either my version or LloydW93 version (which includes calculations for "Conjured Baked Goods" spell) until the official version is updated. To do so, replace the plugin loading code with either:

- My version: 
```
javascript:(function() { Game.LoadMod('https://chorizorro.github.io/CookieMonster/CookieMonster.js');}());
```
- LloydW93's version:
```
javascript:(function() { Game.LoadMod('https://lloydw93.github.io/CookieMonster/CookieMonster.js');}());
```

**Comment by toothstone** [comment]
During my next ascension I was able to track it down to reaching 400 upgrades, which makes sense seeing your commits on the forked CM.

**Comment by toothstone** [comment]
Closing since this seems to be a simple case of having to add the new achievements.
