### ISSUE TITLE
Change stock market scale to go further back in time and show longer stock-history

### ISSUE THREAD

**Issue by faulk28** [Aktanusa/CookieMonster#363]
Can you add an option on the options/settings screen to change the stock market scale?

Ex graph past 60 mins, 24 hours, 72 hours, 1 week, etc

**Comment by DanielNoord** [comment]
This would require us to create more extensive save-data.
We can certainly look into it, but I can't promise anything.

Perhaps asking @staticvariablejames at [InsugarStrading](https://github.com/staticvariablejames/InsugarTrading) wants to implement this?

**Comment by staticvariablejames** [comment]
Spiced Cookies is a better place for this feature than Insugar Trading. I already implemented [saving the stock market history](https://github.com/staticvariablejames/SpicedCookies#save-the-history-of-stock-market-prices-enabled-by-default), for example.

The simple implementation of just storing more data would significantly bloat the save game, though. Each stock market value requires at least 5 bytes to be stored, so storing a week of stock market ups and downs would require a minimum of 160kb. For comparison, a vanilla save is barely 5KB. (I'm assuming you want the stock history to be saved as well, because otherwise you'd have to let the game open for a week straight.)

Maybe I can consider this feature in the future, but not now. Or never, if CM implements it first :)

**Comment by DanielNoord** [comment]
After thinking about this some more I agree with what has been said before and that this will unnecessarily bloat the save file.
It is not something that we will add to CM, but should be doable for another modder. You might want to ask around in the Discord, perhaps there are some people there who might want to take on this project!
