### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Yrlish** [Aktanusa/CookieMonster#38]
I have been noticing that when using this addon, the Cookie Clicker tab uses over 2GB after about an hour. And when not using Cookie Monster, it does not.

I found when I tired to find out what used up all my RAM when everything was being used.

Using the browser Chrome on Linux.
Very late game, six achievements left and about 400k heavenly chips.

**Comment by Aktanusa** [comment]
I used to think the same thing, since FireFox on Windows was crashing after a certain amount of hours.  But then I tested on Chrome for Windows and it never showed up, and eventually apparently there was a bug in FireFox with minimizing the window that caused the memory leak that was fixed and I never had a problem anymore.  Sorry to say, I am leaning towards it being a bug in Chrome for Linux itself.  Are you on the latest version?

**Comment by Aktanusa** [comment]
Additional information:  I was way over 1 mil HC, and actually on FireFox, it would still crash without the addon, but it took longer to do so.  Maybe try again without the addon for a longer time and see if it crashes.

**Comment by Yrlish** [comment]
Yes, I'm on the latest version of Chrome.

**Comment by Yrlish** [comment]
Yea, sure. I'll try without the addon for the rest of the day. Will be annoying not having the additional parts though..

**Comment by Aktanusa** [comment]
I can see that.  Thanks for testing.  Another thing, after FireFox memory leak bug was fixed, I could run both live and beta with CM addon for days without a problem.  Again, sorry to say, but I'm still leaning towards a bug in Chrome for Linux itself.

**Comment by Yrlish** [comment]
I see that the tab's RAM usage is slowly building up, not as fast but it does.. Dammit. :(

**Comment by Aktanusa** [comment]
Sorry to hear, bug Google =p.  Is it safe to close?

**Comment by Aktanusa** [comment]
Also, you might want to update your post in Reddit with what you found.

**Comment by Yrlish** [comment]
Yea, I guess.
