### ISSUE TITLE
Feature requrest: setting to turn off missed golden cookies statistic

### ISSUE THREAD

**Issue by HopesAndMemes** [Aktanusa/CookieMonster#434]
Let me turn off missed golden cookies statistic. I don't like to be able to see this statistic as it is messing with my ocd. I know my experience is not shared, but mere presence of this number is enough to cause annoyance and irritation.

I'd like a setting to turn this statistic off while keeping all the others on.

**Comment by ScriptForAll** [comment]
Well, this feature was originally implemented into Cookie Clicker to be then removed by the same reasons of yours. I can't talk by the development team but since this feature was re-implemented with CM, regardless of its initial reasons to be removed, I reckon this will be something of low priority to be delved into it.

I believe that implementing a turn off setting just for a particular statistic is rather arbitrary and, thus, unnecessary for most people. However, something like a "statistics hider" would something more interesting to be implemented since it would allow the user to pick what statistic suits their needs.

However, there's something one could do in to tackle your issue which is to hide such information by using a adblock's (e.g. uBlock Origin) "Element Picker Mode" feature to hide such information. I've just tried on my CC and it worked. :D

**Comment by HopesAndMemes** [comment]
Thanks, will try

**Comment by DanielNoord** [comment]
It will be fairly easy to implement this into CookieMonster.

However, I am in favor of creating a system to let the user hide certain stats without cluttering the options page. Something like @ScriptForAll describes.
Therefore, at the moment this will not be one of our higher priorities, but I will keep the issue open and return to it once we have cleared some of our backlog.
