### ISSUE TITLE
Move FavIcon and GCTimer options to a better section in the options

### ISSUE THREAD

**Issue by DanielNoord** [Aktanusa/CookieMonster#470]
I moved the `FavIcon` and `GCTimer` settings to Calculation as they didn't fit into Golden Cookie Notifications, but you are right Calculation is also not the right place. I might move them once again to another category, or make a new one for them.

_Originally posted by @DanielNoord in https://github.com/Aktanusa/CookieMonster/issues/445#issuecomment-749510387_

With my fix for #445 I moved the `FavIcon` and `GCTimer` options out of the `Golden Cookie Notification` section. However, their current place is also not currect. We should either place them under another section or create a new section altogether.

**Comment by ScriptForAll** [comment]
I see two possibilities for this:
- Add a "Miscelaneous" category for the kind of options that don't fit anywhere and put these there
- Put the GC Timer option next to the TimerBar option since the number is the same that is shown next to the bar. Even if not very fitting, it's the best solution I can come up with.

**Comment by DanielNoord** [comment]
The new dev-branch version now includes a miscellaneous section.
I think this is the best solution, but plus do tell if you got any other better ideas or Implementations!
