### ISSUE TITLE
Make the bars of individual timers of TimerBar follow the same scale

### ISSUE THREAD

**Issue by SneakyLeif** [Aktanusa/CookieMonster#56]
I noticed that when I gain a Frenzy, both the Frenzy and Next Cookie timers are started at the same length. Say I get a Frenzy and it starts at 154, and the Next Cookie timer starts at ~224 (can't exactly remember). Well what I'm thinking is you could make the length of the Frenzy timer start at the length that the Next Cookie timer would be at that time, if that makes sense. Kind of just have them on the same scale so you'll be able to see how much more Frenzy you'll have when you can get the next cookie.

**Comment by Aktanusa** [comment]
I understand what you mean, but then I guess it all depends on the longest timer and it's max time.  Hmm...

**Comment by Aktanusa** [comment]
A problem I see is the ratio of the bar for Cookie Chain.  Since that's like 3 seconds, the bar will be very small.

**Comment by SneakyLeif1020** [comment]
I'm pretty sure the Next Cookie timer is always longer than the Frenzy timer. And for the Cookie Chain just leave it, since it doesn't need compared to another timer.

**Comment by Aktanusa** [comment]
So only Frenzy and Next Cookie?  It be weird to only apply to Frenzy bar though...

**Comment by SneakyLeif1020** [comment]
Weird is a subjective word. I think it would be great. :)

**Comment by Aktanusa** [comment]
I guess I could add it as an options... I'll think about it.  I will say though, if I do implement it, all of the bars will be scaled.  Would that be okay?

**Comment by SneakyLeif1020** [comment]
Hmm.. I guess it would be okay, but it would be nice if you could somehow override the scaling just for the Cookie Chain timer. But it's okay if you can't as well, since it will be an option. :+1:

**Comment by Aktanusa** [comment]
I can honestly, but me not liking the only Frenzy bar gets the treatment is not sitting well for me, lol.

**Comment by SneakyLeif1020** [comment]
It does seem somewhat weird, but I think it would be a nice change. Just to be able to compare the lengths of the timers with each other seems very practical. Plus when you're in a Cookie Chain there aren't any other timers so there's nothing to compare. Thanks for your input though, it's nice to see you're still actively developing this after so long :D

**Comment by Aktanusa** [comment]
Well I can think of the last option, which is to give people the option for each bar to be ratio or not.  Then you could have it your way where only 1 bar is ratio with the biggest bar.

**Comment by SneakyLeif1020** [comment]
I like that option. :) Thanks!

**Comment by svschouw** [comment]
Actually, it's very likely to be in a frenzy + cookie chain combination. Also, with dragon flight and click frenzy I like the feeling of knowing how far I am percentage-wise, since it's so intense. But also, I would like a more visual representation of whether the click frenzy will end before or after the current frenzy. On the whole, I think I'd agree with @SneakyLeif1020 on "balance all timers except cookie chain".

Btw, there's also the point that the actual 99% window in which the next cookie will appear is a LOT shorter than the whole width of the purple part of the bar. Like, if the timer range is 150 seconds (the purple part), than the 99% percentile point of the next cookie spawning is between 13 seconds and 54 seconds. So even though the "next cookie timer" is longer than the "frenzy timer", the next cookie will almost certainly spawn before the "frenzy timer" runs out. But maybe this is a separate issue.

**Comment by DanielNoord** [comment]
After thinking about this for some time I don't think we should implement this.
It would really depend on a specific combination of buffs and stuff like loan-timers would complicate this.
Therefore, with #147 most of the confusion should be taken away and this is no longer needed/optimal.
