### ISSUE TITLE
Add option to disable GC info in tab title

### ISSUE THREAD

**Issue by Kidsheldon** [Aktanusa/CookieMonster#563]
Previous versions of CM had an option to disable GC info in the game's browser tab title, but now it seems that the title always shows GC timers and the current on-screen GC. Can an option be added back in to disable it?

**Comment by DanielNoord** [comment]
This is indeed a bug. Thanks for reporting.
We still store the setting but don't show it anymore because of a name-change in the settings group.
This should be easily fixed and will be hot-fixed fairly soon!

For myself (or any other contributor), to fix:
Make sure that the group of the entry on line 208 of `Data.js` is actually being drawn.
