### ISSUE TITLE
Combine and splitting information about golden and wrath cookies "Lucky!" reward

### ISSUE THREAD

**Issue by lucmans** [Aktanusa/CookieMonster#60]
As the game is now, the "Lucky!" reward is the same for golden and wrath cookies.
I think showing the values for "Lucky!" MAX looks a bit messy and could be omitted because the both of the "Lucky!" give the same amount

Also the prestige level uses the "tags" CUR and MAX. I had to think for a little but what it meant.
I think a name line "new" or "after ascension" would be better.

I like how to put the "missed golden cookies" back in the game :'). Orteil took it out (or never implemented it) because it would annoy OCD people to much.

**Comment by Aktanusa** [comment]
Due to aura, golden cookies or wrath cookies can get more from "Lucky!".  I guess I could combine them if they are the same and split them when they are not.

I could change it, but CUR and MAX is used everywhere so I wanted to keep it consistent.

Yea, OCD for some people which is why you can minimize it if it affects you.

**Comment by lucmans** [comment]
I have designed interfaces myself and I fully agree it should be consistent. 
But the one thing that is more important in consistent is correctness (in my opinion of course)
Still, it is clear what is meant.

You are right about the auras. I never use those 2 auras so I forgot about them. I think the combining and splitting is a good workaround.

**Comment by Aktanusa** [comment]
Added in Version 2.4
