### ISSUE TITLE
Look into efficiency of the mod

### ISSUE THREAD

**Issue by DanielNoord** [Aktanusa/CookieMonster#621]
**Describe the function you'd like to see added to CookieMonster**
Report on reddit that the mod has become quite resource intensive.
Maybe look into some efficiency upgrades.

**Comment by DanielNoord** [comment]
I feel like 2.031.5 is actually more efficient than 2.031.4, at least my laptop seems to be going into overdrive less.

Can somebody confirm this? Or is the mod still taking up many resources?

**Comment by davidak** [comment]
Yeah, it's a lot smoother. Before, sometimes only 1 in 3 clicks was recognized, so you always miss cookie chains. Now that's not an issue anymore. It still runs a little slow at times, so more performance improvements would be great if possible. I have quiet high-end hardware (i9, 32 GB RAM), so it might be worse for others.

**Comment by DanielNoord** [comment]
Do you know perhaps know when such lag spikes occur? Is it after a certain action/click? Or do they seem random?

**Comment by davidak** [comment]
Disclaimer 1: My system is very overloaded, because i have too many tabs open (more than 1000) and the RAM and SWAP is nearly full.
Disclaimer 2: The game also runs slow without the add-on loaded. But a bit more performant.

One thing i recognized is that every time a golden cookie appears, the big cookie disappears for a second and the background went black. That does not happen without the add-on.

I have disabled the sound and notifications, but maybe the code still runs and add lag?

I guess it's just a lot of JS calculations going on in the background that adds extra lag to the general game. That's why it runs a bit faster without the add-on.

I have a video that demonstrates it, including the game freezing for like 20 seconds: https://youtu.be/zOtBEArHYTU

Most of it is probably my own fault, but it might simulate how a very low-end system would perform, especially when you use other programs in addition to it.

**Comment by DanielNoord** [comment]
That flickering is somethings I will investigate. Just to be sure, could you share you save so I have the same display settings to test with?
