### ISSUE TITLE
No green buy items for 10 or 100 buildings

### ISSUE THREAD

**Issue by faulk28** [Aktanusa/CookieMonster#633]
If x1 is selected in the buy/sell column I see a green item (the most cost effective to buy)

This no longer works for x10 or x100

Instead all items are yellow and there is a single purple item. Is this a bug or what?

**Comment by DanielNoord** [comment]
This sounds similar to #631, could you check if that is true?

**Comment by faulk28** [comment]
It’s the same issue I believe. Can you tell me where that exact option is?
I hit sort buildings by PP and that made it easier. Can you make it so the
lowest PP estimate is green? Why would you not want to show the lowest PP?
Or how about the top 3 buildings green? Doesn’t make sense to make them all
yellow.

Thanks so much for your help and hard work

**Comment by DanielNoord** [comment]
The setting is under the "Calculation" section in the settings. It currently (probably) set to "Color of PP (Compared to Single)".
It shows yellow colors when you have selected 10 or 100 buildings because there is actually an option with a lower PP: "buy 1".
By changing that setting it will show the most optimal building for the current selected mode. In your current state it compares it to the best "buy 1" option, which in this case is better than any of the buy 10 or buy 100 options. Have I cleared it up for you? Or do I need to explain it in more detail?
