### ISSUE TITLE
RoI with 'lucky cookie required'

### ISSUE THREAD

**Issue by hypraman** [Aktanusa/CookieMonster#67]
I loooove the new RoI formula, good job on it!
If i understand it, it now also calculate the 'waiting time to buy' so that it don't make a insanely expansive upgrade the 'blue' one.

But i have this issue where most of the time, I do already have enough for the upgrade or building, but i don't want to buy it, because it will put me under the cookie amount i require to get the most out of my Golden cookies. 
This makes the new formula less of a useful thing considering it thinks i don't have to wait to gain more cookies to buy it... but i have to, as it gives me the warning/caution that it will bring me under the limit.

I know it's picky, but is there a way to add an option to make the RoI calculator to think I have (current cookie) - (cookies needed for Lucky frenzy with the bonus CPS), and not only ( current cookies ), something like that???

Not sure if it make sense or if you get my point >.o;

**Comment by Aktanusa** [comment]
I get what you mean though it be tricky in terms of what options to give.  Is it just "Lucky!" bank? or "Lucky!" + Frenzy bank?  Is the bank needed with the CPS before the purchase of the item or the CPS after the purchase of the item?  That's 4 extra choices there.

**Comment by hypraman** [comment]
I always keep the full bank: Lucky! + frenzy + Added bonus CPS of the building/upgrade

I keep the 'Calculate Warning/Cautions with bonus CPS' on mostly because of the kitten upgrade that more than doubles it, drastically reducing the amount of cookie below the required amount most of the time.

The problem goes to whoever keep cookies stored for anything, may it be for golden cookies bonus or chocolate egg etc... and what to keep that amount

**Comment by Aktanusa** [comment]
What I mean is, while you like to keep it Lucky! + Frenzy + Added bonus, someone else might want a different option.  Basically I'm just complaining I need to add more stuff to options =p

**Comment by hypraman** [comment]
oooooh yes that makes sense.
Sorry for the weight of my request/suggestion then ^^;

**Comment by Skaramuche** [comment]
Hi! Just wanted to chime in to request this feature as well. The whole plugin is wildly useful and slick—thank you so much!—but that's definitely the #1 thing that would make it better.

I understand the appeal of "calculate with bonus CPS" because of the dread one starts to get of being under the lucky threshold, but I think it's actually an illusory problem. If you double your CPS and therefore double your lucky threshold, then your return R on a GC becomes half its maximum instead of all of its maximum...but R didn't go DOWN, the max just went UP. You're still getting as much as you possibly could. Waiting to buy the upgrade until you have your new maximum just means that, in the meantime, you're getting R...R...R...R...2R. If you bought the upgrade as soon as it was safe with current threshold, you'd get R...1.1R...1.2R...1.4R...1.7R...2R; it's better to raise the max as soon as possible even if it leaves you far below the threshold.

**Comment by Aktanusa** [comment]
The "calculate with bonus CPS" has always been less efficient.  It's there as you say for illusion really.  For those OCD who don't ever want to be under the bank.  It's why it's off by default since it is less efficient.  As for @hypraman's request, yea I've been slacking for a bit and lost a bit of interest, but hopefully I'll get to it eventually.  Sorry for the wait and thanks for being patient with me!

**Comment by Skaramuche** [comment]
Don't worry about it all—it's awesome of you to do all this for free anyhow, we certainly have no right to expect more. :) Do it when you feel the need, or not at all. Thanks again!

**Comment by DanielNoord** [comment]
As @Aktanusa said this would inflate the options as we add more warnings and therefore possible combinations of warnings to take into account. We are currently at 3 types, giving already 8 different possible combinations.
I believe the tooltip with the option to calculate it using bonus income already gives the information requested;
If the lowest PP-building gives you a warning, don't buy the upgrade. Adding it to the calculation therefore doesn't add any info that is not already available in another way and only inflates the options panel.

(Keep in mind that the PP is not actually a time-period and adding warning-thresholds into the calculation would thus not tell you how long you have to wait, as the PP already does not tell you this)
