### ISSUE TITLE
Host previous versions or provide instructions on how to use them

### ISSUE THREAD

**Issue by dhouck** [Aktanusa/CookieMonster#670]
**Describe the function you'd like to see added to CookieMonster**
Given the several bugs found within the first few hours of the 2.031.5 release, I attempted to downgrade to 2.031.4 until things had been fixed.  However, I can't find how to do that.  Changing the user script to point to https://gitcdn.link/repo/Aktanusa/CookieMonster/f3617d5fc2c8e9e807a9dcdc16a444f577b21d69/CookieMonster.js got closest, but apparently the mod is not a self-contained file, so this failed looking for other files on the aktanusa.github.io site.

**Comment by DanielNoord** [comment]
The problem is that the previous version relied on hosting code that was not actually ours. One of the reasons for the complete rewrite of the code in 2.031.5 was to remove this dependency and import this module correctly.
This is also why previous versions are now broken. While I understand that backwards compatibility and supporting previous versions is important I think in this case it is unavoidable to lose support for previous versions.

I do try to fix all critical bugs as quickly as possible though. I have just fixed the last open bugs this morning and I hope everything is working and calculating correctly now. I predict/hope that we will not need any major updates like this in the future, which should also limit the risk to introduce major mod-breaking bugs.
I am also considering writing some tests for the mod to run before pushing new versions. Although it is quite a task to retroactively write tests for a mod that is already 30k+ lines of code.

**Comment by dhouck** [comment]
Okay, that makes sense.  And if you got rid of the dependencies on external code then it sounds like this might be possible if there are future major releases even if it wasn't this time?

**Comment by DanielNoord** [comment]
Yeah, normally this shouldn't be a problem.
We still use the external code, but do so via the official channel instead of re-uploading it ourselves. The current version of Cookie Monster does not load anything outside of the initial besides the favicon. As I don't expect much will change to the favicon I don't expect any problems with backward compatibility in the future.
