### ISSUE TITLE
Rename Return on Investment

### ISSUE THREAD

**Issue by Appleguysnake** [Aktanusa/CookieMonster#68]
From conversation [here](https://github.com/Aktanusa/CookieMonster/issues/28#issuecomment-199878076)

Suggestions:

- Return-Adjusted Cost
- Bank-Adjusted Cost
- Modified Cost

**Comment by svschouw** [comment]
Let me add "Break Even Point". I mentioned the term "Return on Investment" thinking it was actually just another name of "Return on Investment" (the amount of time it takes to return the investment), but it was actually something different. I did think at that time that "Break Even Point" might be technically better, but "Return On Investment" just sounded a lot nicer.

I'm not really in favor of a "cost" term, because it's not really a cost in a monetary ("cookietary"?) sense. The formula comes down to a time unit, namely the time in seconds from this moment until you have the exact same amount of cookies whether you buy the investment or not. Although you could say it's a time cost.

That said, I don't particularly care about the name.

**Comment by Appleguysnake** [comment]
Wait, so you mean when I mouseover a Prism right now and it says ROI: 9.463 million - that's referring to 9 million seconds? I assumed that was cookies. That would be even more reason to change the name. If that's the case, "Time to recoup" or something like that could work. 

I know the name isn't functionally important, but it does make a big difference in the ease of use for people who haven't read the formula.

**Comment by svschouw** [comment]
Yup, it's seconds. And you're right, that might also be a very good reason to change the name.

**Comment by Aktanusa** [comment]
If you think about it, BCI is basically the amount of time the bonus CPS will take to pay for the cost of the bonus CPS.

**Comment by Aktanusa** [comment]
How about Recuperate Amount Recuperate Time?

**Comment by Appleguysnake** [comment]
I realized we were trying to re-invent the wheel so I googled for a term and found one: [Payback Period](https://en.wikipedia.org/wiki/Payback_period). I suggest that as the term, if it really is a measure of time. If it's a measure of cost, then I'd stick with one of my original suggestions.

Which brings up another thing that makes this confusing - there are no units attached to that number, so it's even harder to intuitively figure out what it is. Just something to keep in mind, I don't know if there really are any units that could accurately be attached.

**Comment by Aktanusa** [comment]
well I was trying not to re-invent the wheel, but doing Google searches I couldn't find a good fitting term, lol.  Glad you found one.

As for the units, it is technically seconds, since it is the time taken to get enough in the bank to buy plus the time taken for the bonus CPS to pay back the cost, but it may confuse people on why are we adding those times so I think it is best to leave the unit out.

**Comment by Aktanusa** [comment]
Oh yea, I plan to change it to Payback Period as it really fits it now.

**Comment by Appleguysnake** [comment]
Well if it's seconds, I think that could be useful, because it could be converted to minutes/hours. That was actually one of the first features I looked for when I found this add-on! I found the amortization info option and actually thought that's what it was (explaining how long it would take to pay back before purchasing instead of after). Because really, I understand "lower is better" but beyond that "9 million seconds" doesn't mean much to me haha.

PS. I find it hilarious that the first thing I'm actually spending time with on GitHub is text in a Cookie Clicker add-on instead of an actual programming project. I've clearly got good priorities.

**Comment by Aktanusa** [comment]
The amortization stat is somewhat not too useful because of two thing:

1.  It doesn't account for the bonus CPS you get from other things besides buying the building (like gain an achievement that boost kitten productivity)
2.  Due to the long standing bug in CC that the amount of cookies gained by a building is saved as an integer, when you get to late game, the number gets reset after every refresh due to overflow

This is why the stat is off by default, but it was requested as an enhancement and not too hard to implement, so why not.

I'll think about adding units, but blah if I need to convert seconds to mins or hours, lol.  I also like the term "Payback Period" since it doesn't actually mention the word "Time" even though the word "Period" should imply time.

As for your PS, you're not the first person signing up to github just to comment on this addon...  I was quite surprise how many people have done it =p.

**Comment by Appleguysnake** [comment]
That all sounds pretty good. Thank you for putting so much work into this project!

**Comment by Aktanusa** [comment]
Honestly, since I already have a method to change seconds to day/hour/min/second, I may add units if the formula is change to what I suggested in Issue #3.

**Comment by Aktanusa** [comment]
@svschouw What are your thoughts on adding units since it is really time?

**Comment by svschouw** [comment]
I have no preference. To me it's just "lower is better". In fact, I don't really even look at the number, since I just go for the blue/green one :)

**Comment by Aktanusa** [comment]
Changed in Version 2.5
