### ISSUE TITLE
If you click many times in a golden cookie with this mod you can get multiple buffs

### ISSUE THREAD

**Issue by RandomNumbers09** [Aktanusa/CookieMonster#701]
**Describe the bug**
Please describe the bug and what you would have expected the mod to do

**To Reproduce**
The steps needed to reproduce the behavior:
1. ...

**Screenshots**

**Save file**
```
Please add a save file here.
This makes debugging much easier as we do not always have a good test save to debug the issue
```

**Comment by RandomNumbers09** [comment]
If you don't understand what i'm saying, my bad, my english is terrible

**Comment by DanielNoord** [comment]
Do you use any other mods? I have seen this bug before (many times) and they are often related to auto-clickers. This is not something Cookie Monster provides and I am inclined to say that the bug you are seeing is not actually caused by Cookie Monster but probably by another mod.
If you are not using another mod, could you provide your save-file? I will be happy to investigate if this is not the case.
