### ISSUE TITLE
Add option to display in Title if GC can appear

### ISSUE THREAD

**Issue by CatsAreFluffy** [Aktanusa/CookieMonster#73]
When the gray section disappears, it should show in title.

**Comment by Aktanusa** [comment]
While this is a good suggestion, how do you propose to show that in the title?

**Comment by CatsAreFluffy** [comment]
I don't know, an ! after the [?

**Comment by Aktanusa** [comment]
Hmm...  Something like that may work

**Comment by Aktanusa** [comment]
Hmm, I just thought of another way.  How about have the numbers be negative with it going towards 0 when it's grey then a regular countdown?

**Comment by CatsAreFluffy** [comment]
Maybe.

**Comment by orangy** [comment]
How about countdown normally, and when the chance is above 50%, replace with [%50] and go upward with chances?

**Comment by JCBourgo** [comment]
I'm thinking of a [XXX-YYY] format. The X means the time remaining before a GC CAN appear and the Y is the time before a GC HAS TO appear. Therefore, when a GC can appear, X will be at 0 and Y will show the maximum time left.

**Comment by svschouw** [comment]
It's all very artificial, since there's pretty much no chance the cookie appears at the start of the purple bar, and it will have appeared long before the end. It kindof looks like a normal distribution (in the statistical sense). I did the math, but it's pretty complicated and heavily depends on which of all the golden cookie upgrades you have and even things like framerate.

Still, after a while you learn to recognize the point where the cookie is likely to appear.

Also, @orangy, 50% of what? Because by the time the purple bar is halfway done, the cookie will have appeared with > 95% chance.

**Comment by JCBourgo** [comment]
There has to be a way to at least approximate the cookie spawn chances per frame or second. Like in 10% increments maybe.

**Comment by orangy** [comment]
50% chance to happen in the next, say, 5 seconds.

**Comment by svschouw** [comment]
Per frame is easy; that's `(ticks/total_ticks)^5`. (Where "ticks" is the amount of ticks into the purple bar, and "total_ticks" is the total amount of ticks of the purple bar). But if that reaches 10%, with 30 fps the chance of the cookie spawning that second is already 94%, which means the seconds before that also had similar high chances, so you're never reaching that far. Per second can be approximated with `1-(1-(ticks/total_ticks)^5)^30`, but I wouldn't be surprised if that would never reach 50% as well.

*Doing more math*

Yeah, in my example condition (all lucky upgrades + golden goose iirc), the average spawn is 36 seconds into the purple timer. At that point the chance per tick is 0.3% and the approximated chance per second is 9.4%. By the time the chance per second reaches 50%, the spawn chance is around 99.98%

**Comment by Aktanusa** [comment]
I do like the idea of showing chance of it spawning, but right now I wouldn't know how to calculate it.  The math @svschouw does is over my head (more like too lazy to think about it right now >_<).

**Comment by svschouw** [comment]
It's actually not super hard. The main problem here is precision. Computers are good at small values for X, but not so good at multiplying lots of (1-X)'s for very small Xs. However, this is mainly a problem in the extremes of the timeline and if you want to calculate the entire distribution. In the interesting part of the timeline the Xs are big enough for computers to handle (1-X) just fine.

So the game runs in 30 ticks per second. With all the lucky upgrades, but without any other upgrades the cookie spawns between 75 en 225 seconds after the last golden cookie. This is a 150 second window, or 30 * 150 = 4500 ticks. All golden cookie spawn-chance related upgrades just modify the window.

Now, like said earlier, the chance of a cookie spawning every tick is defined as
`Pspawn(tick) = (tick/total_ticks)^5`
where `tick` is the tick since the start of the window, and `total_ticks` is the total window size in ticks. There is no math involved here, this is just how it is defined in the code.

Now the chance of a cookie spawning in the next second is 1 minus the chance of a cookie *not* spawning in the next second. And the chance of the cookie not spawning is
`(1 - Pspawn(tick)) * (1 - Pspawn(tick+1)) * (1 - Pspawn(tick+2)) * ... * (1 - Pspawn(tick+29))`
Since `Pspawn(tick)` is not that different from `Pspawn(tick+30)` we can approximate this by `(1 - Pspawn(tick))^30`, or even better, by taking the spawn chance halfway the test-window: `(1 - Pspawn(tick+15))^30`.
So then the approximate chance of the cookie spawning in the next `w` ticks is:
`Pspawnwindow(tick, w) = 1 - (1 - Pspawn(tick+w/2))^w = 1 - (1 - ((tick+w/2)/total_ticks)^5)^w`
Of course, the bigger the `w`, the less accurate this is, but for 5 seconds it still seems pretty accurate.

**Comment by Aktanusa** [comment]
Given that usually the title updates once a second, do I just plug 1 in w in your above formula and I would get a spawn chance?

**Comment by orangy** [comment]
I don't think that 1 second is good interval. It's more of UX stuff, so if I think it's time to click there already and just wait for a splash, or still read my lazy web waiting for a G-spot ;)

**Comment by Aktanusa** [comment]
@orangy Sorry to say, you lost me.  What's UX stuff?

**Comment by orangy** [comment]
UX = User Experience. What's user story here? What's the expectation? Why user wants it? Right now I'm already used to click into tab around 100 "intrinsic time" – if it's happened already, I still have time to click. If it didn't happen, it's very likely to happen right away.

**Comment by Aktanusa** [comment]
Ah, gotcha, but unless I completely misunderstood, what I meant by 1 second is 1 second interval updates.  So if I read what @svschouw wrote correctly, if I plug in 1 for w in his formula, I would get the spawn chance that second.  So if I update that spawn chance in the title every 1 second, you would switch to the tab when the % gets high enough.

**Comment by svschouw** [comment]
Sorry for the wait, but `w` is in ticks, so if you want 1 second, you should plug in 30.

**Comment by JCBourgo** [comment]
By the way, I think we deviated a lot from the original issue. The first request was to show in the title whether or not a GC can appear. Why all the complicated stuff?

**Comment by Aktanusa** [comment]
@svschouw so I plug in 30 and it should be fine?  You said 5 seconds (w= 150) seems fine, right?

@JCBourgo I think it's still related.  To show what is your chance of spawning with it be 0% during grey bar still does what the original issue asks.

**Comment by svschouw** [comment]
@Aktanusa Yes, 150 ticks = 5 sec and that looks pretty aight (maybe 1 or 2 % off, but I don't think that matters very much).

**Comment by Aktanusa** [comment]
So doing percent should be good for you?

**Comment by svschouw** [comment]
Well, it's a nice statistic; and if you put it in the title it does give you a better idea on when to pay attention maybe. Although personally I'd just go for the sound anyway.

**Comment by Aktanusa** [comment]
Personally, I got sick of the sound, as I would have to stop drop whatever I was doing and go and click it, lol.  This is my style of playing CC though in which I mostly only idle now.
