### ISSUE TITLE
time left bug?

### ISSUE THREAD

**Issue by Kantaga** [Aktanusa/CookieMonster#92]
When using Cookie Monster, often the time left messes up. It will sometimes just freeze in a time which isn't anywhere near the real time.

**Comment by Aktanusa** [comment]
It's based on average CPS now.  There is an option to revert back to current CPS.  You could also change the history used to calculate average CPS to see if you can get it closer to the update you want.  In my opinion, average CPS would be closer to the real time left since it does account for Wrinklers and Golden Cookies.

**Comment by Kantaga** [comment]
Oh, thank you.

**Comment by Aktanusa** [comment]
Can I close this?

**Comment by Aktanusa** [comment]
Closing due to lack of response.

**Comment by dlsso** [comment]
I don't see any information on how to set this option. Could you put instructions in the readme?

**Comment by Aktanusa** [comment]
It's the option that says "Average Cookies Per Second" which would change to "Current Cookies Per Second" which you click on it.
